### ISSUE TITLE
why you use these three numbers?

### ISSUE THREAD

**Issue by Perfeee** [fducau/AAE_pytorch#3]
In aae_pytorch_basic.py, line 181 and line 212, those three constants are used for what? and how do you choose those? BTW, please forgive my poor english.... Thank you in advance.

**Comment by fducau** [comment]
Line [181](https://github.com/fducau/AAE_pytorch/blob/master/script/aae_pytorch_basic.py#L181) is to normalize the input images. 
Line [212](https://github.com/fducau/AAE_pytorch/blob/master/script/aae_pytorch_basic.py#L212) there is a constant 5 used to get samples from a normal distribution with standard deviation equal to 5.
